local M = {}

local palette = {
  black = "#100F0F",
  base950 = "#1C1B1A",
  base900 = "#282726",
  base850 = "#343331",
  base800 = "#403E3C",
  base700 = "#575653",
  base600 = "#6F6E69",
  base500 = "#878580",
  base400 = "#9F9D96",
  base300 = "#B7B5AC",
  base200 = "#CECDC3",
  base150 = "#DAD8CE",
  base100 = "#E6E4D9",
  base50 = "#F2F0E5",
  paper = "#FFFCF0",
  red600 = "#AF3029",
  red400 = "#D14D41",
  red200 = "#F89A8A",
  orange600 = "#BC5215",
  orange400 = "#DA702C",
  orange200 = "#F9AE77",
  yellow600 = "#AD8301",
  yellow400 = "#D0A215",
  yellow200 = "#ECCB60",
  green600 = "#66800B",
  green400 = "#879A39",
  green200 = "#BEC97E",
  cyan600 = "#24837B",
  cyan400 = "#3AA99F",
  cyan200 = "#87D3C3",
  blue600 = "#205EA6",
  blue400 = "#4385BE",
  blue200 = "#92BFDB",
  purple600 = "#5E409D",
  purple400 = "#8B7EC8",
  purple200 = "#C4B9E0",
  magenta600 = "#A02F6F",
  magenta400 = "#CE5D97",
  magenta200 = "#F4A4C2",
}

M.colors = {
  bg = palette.paper,
  bg2 = palette.base50,
  ui = palette.base100,
  ui2 = palette.base150,
  ui3 = palette.base200,
  tx3 = palette.base300,
  tx2 = palette.base600,
  tx = palette.black,
  red = palette.red600,
  red2 = palette.red400,
  red3 = palette.red200,
  orange = palette.orange600,
  orange2 = palette.orange400,
  orange3 = palette.orange200,
  yellow = palette.yellow600,
  yellow2 = palette.yellow400,
  yellow3 = palette.yellow200,
  green = palette.green600,
  green2 = palette.green400,
  green3 = palette.green200,
  cyan = palette.cyan600,
  cyan2 = palette.cyan400,
  cyan3 = palette.cyan200,
  blue = palette.blue600,
  blue2 = palette.blue400,
  blue3 = palette.blue200,
  purple = palette.purple600,
  purple2 = palette.purple400,
  purple3 = palette.purple200,
  magenta = palette.magenta600,
  magenta2 = palette.magenta400,
  magenta3 = palette.magenta200,
}

local options = {}

local function highlights(c)
  return {
    Normal = { fg = c.tx, bg = c.bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.tx, bg = c.bg2 },
    FloatBorder = { fg = c.ui3, bg = c.bg2 },
    FloatTitle = { fg = c.blue, bg = c.bg2, bold = true },
    ColorColumn = { bg = c.bg2 },
    Cursor = { fg = c.bg, bg = c.tx },
    CursorColumn = { bg = c.bg2 },
    CursorLine = { bg = c.bg2 },
    CursorLineNr = { fg = c.tx, bg = c.bg2, bold = true },
    LineNr = { fg = c.tx3 },
    SignColumn = { fg = c.tx3, bg = c.bg },
    FoldColumn = { fg = c.tx3, bg = c.bg },
    Folded = { fg = c.tx2, bg = c.bg2 },
    EndOfBuffer = { fg = c.bg },
    NonText = { fg = c.ui3 },
    Whitespace = { fg = c.ui3 },
    Conceal = { fg = c.tx3 },
    Directory = { fg = c.blue },
    MatchParen = { fg = c.magenta, bg = c.ui, bold = true },
    Search = { fg = c.tx, bg = c.yellow3 },
    IncSearch = { fg = c.bg, bg = c.orange },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = c.bg, bg = c.red },
    Visual = { bg = c.ui2 },
    VisualNOS = { bg = c.ui },
    Pmenu = { fg = c.tx, bg = c.bg2 },
    PmenuSel = { fg = c.tx, bg = c.ui2, bold = true },
    PmenuSbar = { bg = c.ui },
    PmenuThumb = { bg = c.ui3 },
    StatusLine = { fg = c.tx, bg = c.ui },
    StatusLineNC = { fg = c.tx3, bg = c.bg2 },
    TabLine = { fg = c.tx2, bg = c.bg2 },
    TabLineFill = { bg = c.bg2 },
    TabLineSel = { fg = c.tx, bg = c.bg, bold = true },
    WinBar = { fg = c.tx2, bg = c.bg },
    WinBarNC = { fg = c.tx3, bg = c.bg },
    WinSeparator = { fg = c.ui },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.bg, bg = c.blue },
    Question = { fg = c.cyan },
    MoreMsg = { fg = c.cyan },
    WarningMsg = { fg = c.orange },
    ErrorMsg = { fg = c.red, bold = true },
    Title = { fg = c.orange, bold = true },

    Comment = { fg = c.tx3, italic = true },
    Constant = { fg = c.yellow },
    String = { fg = c.cyan },
    Character = { fg = c.cyan },
    Number = { fg = c.purple },
    Boolean = { fg = c.purple },
    Float = { fg = c.purple },
    Identifier = { fg = c.blue },
    Function = { fg = c.orange },
    Statement = { fg = c.green },
    Conditional = { fg = c.green },
    Repeat = { fg = c.green },
    Label = { fg = c.green },
    Operator = { fg = c.tx2 },
    Keyword = { fg = c.green },
    Exception = { fg = c.green },
    PreProc = { fg = c.red },
    Include = { fg = c.red },
    Define = { fg = c.magenta },
    Macro = { fg = c.magenta },
    PreCondit = { fg = c.red },
    Type = { fg = c.yellow },
    StorageClass = { fg = c.magenta },
    Structure = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Special = { fg = c.magenta },
    SpecialChar = { fg = c.magenta },
    Tag = { fg = c.blue },
    Delimiter = { fg = c.tx2 },
    SpecialComment = { fg = c.tx3, italic = true },
    Debug = { fg = c.red },
    Underlined = { fg = c.cyan, underline = true },
    Ignore = { fg = c.tx3 },
    Error = { fg = c.red },
    Todo = { fg = c.magenta, bg = c.bg, bold = true },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.orange },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },

    ["@comment"] = { link = "Comment" },
    ["@comment.todo"] = { link = "Todo" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.purple },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.magenta },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@variable"] = { fg = c.blue },
    ["@variable.builtin"] = { fg = c.magenta },
    ["@variable.parameter"] = { fg = c.blue },
    ["@property"] = { fg = c.blue },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.orange },
    ["@function.macro"] = { fg = c.magenta },
    ["@constructor"] = { fg = c.orange },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.import"] = { fg = c.red },
    ["@keyword.function"] = { fg = c.green },
    ["@keyword.return"] = { fg = c.green },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.yellow },
    ["@attribute"] = { fg = c.blue },
    ["@punctuation"] = { fg = c.tx2 },
    ["@punctuation.bracket"] = { fg = c.tx2 },
    ["@punctuation.delimiter"] = { fg = c.tx2 },
    ["@tag"] = { fg = c.blue },
    ["@tag.attribute"] = { fg = c.orange },
    ["@markup.heading"] = { fg = c.orange, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.cyan, underline = true },
    ["@markup.raw"] = { fg = c.cyan },
    ["@markup.list"] = { fg = c.magenta },
    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.orange },

    LspReferenceText = { bg = c.ui },
    LspReferenceRead = { bg = c.ui },
    LspReferenceWrite = { bg = c.ui2 },
    ["@lsp.type.namespace"] = { fg = c.yellow },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.parameter"] = { fg = c.blue },
    ["@lsp.type.variable"] = { fg = c.blue },
    ["@lsp.type.property"] = { fg = c.blue },
    ["@lsp.type.enumMember"] = { fg = c.yellow },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.macro"] = { fg = c.magenta },

    DiffAdd = { fg = c.green, bg = c.bg2 },
    DiffChange = { fg = c.orange, bg = c.bg2 },
    DiffDelete = { fg = c.red, bg = c.bg2 },
    DiffText = { fg = c.tx, bg = c.yellow3, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.orange },
    Removed = { fg = c.red },
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.orange },
    GitSignsDelete = { fg = c.red },

    TelescopeNormal = { fg = c.tx, bg = c.bg },
    TelescopeBorder = { fg = c.ui2, bg = c.bg },
    TelescopePromptNormal = { fg = c.tx, bg = c.bg2 },
    TelescopePromptBorder = { fg = c.ui2, bg = c.bg2 },
    TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
    TelescopePreviewTitle = { fg = c.green, bold = true },
    TelescopeResultsTitle = { fg = c.orange, bold = true },
    TelescopeSelection = { bg = c.ui },
    TelescopeMatching = { fg = c.orange, bold = true },
    WhichKey = { fg = c.magenta },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.tx },
    WhichKeySeparator = { fg = c.tx3 },
    WhichKeyFloat = { bg = c.bg2 },
    NeoTreeNormal = { fg = c.tx, bg = c.bg },
    NeoTreeNormalNC = { link = "NeoTreeNormal" },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeRootName = { fg = c.orange, bold = true },
    NeoTreeGitAdded = { fg = c.green },
    NeoTreeGitModified = { fg = c.orange },
    NeoTreeGitDeleted = { fg = c.red },
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder = { fg = c.orange },
    NotifyINFOBorder = { fg = c.blue },
    NotifyDEBUGBorder = { fg = c.tx3 },
    NotifyTRACEBorder = { fg = c.magenta },
    NoiceCmdlinePopupBorder = { fg = c.blue },
    NoiceCmdlineIcon = { fg = c.blue },
    SnacksPicker = { fg = c.tx, bg = c.bg2 },
    SnacksPickerBox = { fg = c.tx, bg = c.bg2 },
    SnacksPickerBoxBorder = { fg = c.ui2, bg = c.bg2 },
    SnacksPickerInput = { fg = c.tx, bg = c.bg2 },
    SnacksPickerInputBorder = { fg = c.ui2, bg = c.bg2 },
    SnacksPickerInputTitle = { fg = c.blue, bg = c.bg2, bold = true },
    SnacksPickerList = { fg = c.tx, bg = c.bg2 },
    SnacksPickerListBorder = { fg = c.ui2, bg = c.bg2 },
    SnacksPickerListTitle = { fg = c.blue, bg = c.bg2, bold = true },
    SnacksPickerListCursorLine = { bg = c.ui },
    SnacksPickerPreview = { fg = c.tx, bg = c.bg },
    SnacksPickerPreviewBorder = { fg = c.ui2, bg = c.bg },
    SnacksPickerPreviewTitle = { fg = c.blue, bg = c.bg, bold = true },
    SnacksPickerPreviewCursorLine = { bg = c.ui },
    SnacksPickerPreviewLineNr = { fg = c.tx3, bg = c.bg },
    SnacksPickerPreviewSignColumn = { fg = c.tx3, bg = c.bg },
    SnacksPickerPreviewFoldColumn = { fg = c.tx3, bg = c.bg },
    SnacksPickerMatch = { fg = c.orange, bold = true },
    SnacksPickerSelected = { bg = c.ui },
    BlinkCmpMenu = { fg = c.tx, bg = c.bg2 },
    BlinkCmpMenuSelection = { bg = c.ui2 },
    BlinkCmpLabelMatch = { fg = c.orange, bold = true },
    RenderMarkdownCode = { bg = c.bg2 },
    RenderMarkdownCodeInline = { fg = c.cyan, bg = c.bg2 },
  }
end

function M.setup(opts) options = opts or {} end

function M.load()
  vim.o.termguicolors = true
  vim.o.background = "light"
  vim.cmd.highlight "clear"
  if vim.fn.exists "syntax_on" == 1 then vim.cmd.syntax "reset" end
  vim.g.colors_name = "flexoki"

  local groups = highlights(M.colors)
  if type(options.highlight_override) == "function" then
    groups = vim.tbl_deep_extend("force", groups, options.highlight_override(M.colors) or {})
  end
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end

  local terminal = {
    palette.black,
    M.colors.red,
    M.colors.green,
    M.colors.yellow,
    M.colors.blue,
    M.colors.magenta,
    M.colors.cyan,
    palette.base200,
    palette.base600,
    M.colors.red2,
    M.colors.green2,
    M.colors.yellow2,
    M.colors.blue2,
    M.colors.magenta2,
    M.colors.cyan2,
    palette.paper,
  }
  for index, color in ipairs(terminal) do
    vim.g["terminal_color_" .. index - 1] = color
  end
end

return M
